# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xJOmy8cMqwuKekpc-S4nR7ebmWPwCitu
"""

import pandas as pd
import numpy as np

data = {
    'Student_Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'Math_Score': [85, 42, 90, 30, 95, 60],
    'English_Score': [88, 50, 92, 40, 98, 55],
    'Attendance_Pct': [95, 60, 98, 50, 100, 75]
}
df_dummy = pd.DataFrame(data)
df_dummy.to_csv('student_scores.csv', index=False)

df = pd.read_csv('student_scores.csv')

print(df.head())
print(df.tail())
print(df.dtypes)

print(df.describe())

passing_math = df[df['Math_Score'] > 40]
final_report = passing_math[['Student_Name', 'Math_Score']]

print(final_report)

final_report.to_csv('passing_students.csv', index=False)